platform :ios, '7.0'

target 'Sword' do

pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 4.0.0'
pod 'PureLayout'
pod 'ReactiveCocoa', '~> 2.5', :inhibit_warnings => true
pod 'YYText'
pod 'pop'
pod 'SVProgressHUD'
pod 'MJRefresh'
#个推
pod 'GTSDK', '~> 1.6.2-noidfa'
pod 'Bugly'
pod 'SensorsAnalyticsSDK'
pod 'SSZipArchive'

end

target 'SwordTests' do

pod 'OCMock', '~> 3.3.1'

end
